### ISSUE TITLE
Move translations to a dedicated platform

### ISSUE THREAD

**Issue by picsi** [pixelfed/project-website#35]
Pixelfed is going to grow a lot very soon, it seems, so in order to keep strings updated in multiple languages (as well as to make it easier to translate), it would be ideal to move translations to an external platform.

I suggest translatewiki.net, as it works well for projects like Wikipedia and OpenStreetMap, and has a sizeable community.

**Comment by trwnh** [comment]
Weblate also works well for this, and I think can automatically merge into git? It's what the Mastodon translations use.

**Comment by picsi** [comment]
I have had good experiences with Weblate (as well as Transifex). 

The reason I recommended translatewiki.net is because of its community. I've seen folks who never used a project translating it into several languages: https://translatewiki.net/w/i.php?title=Special:MessageGroupStats&language=eo&group=page-Translating%3ALib.reviews%2FFAQ#sortable:3=desc

Because translatewiki hosts such big free software projects, folks who are already there end up translating other projects when they're bored, it seems.

**Comment by allvoxman** [comment]
Crowdin is OK too.
