### ISSUE TITLE
Caption limit hit, no warning, cleared what I tried to post/write

### ISSUE THREAD

**Issue by mal0ki** [pixelfed/project-website#50]
"The caption may not be greater than 150 characters" Which I wasn't warned about until after I had tried posting a bigger one. And everything was cleared when I tried to post.

Suggestion: 
[ ] Character counter / countdown
[ ] Don't clear all the submitted data, ie, save the draft I guess?

Bonus:
[ ] Possibly more than 150 characters, even if the focus is on photos, sometimes we have a lot to say about a work of art, or a photo or something. 

![image](https://user-images.githubusercontent.com/28316305/40858076-68c50216-65dd-11e8-9b05-29e2bc2ce35e.png)

**Comment by dansup** [comment]
Closed see https://github.com/dansup/pixelfed/issues/121
