### ISSUE TITLE
[[Feature]] Display Version the Site is Running

### ISSUE THREAD

**Issue by WammKD** [pixelfed/project-website#58]
This may already be the case and I just couldn't easily find it but showing the version of Pixelfed being run on a respective instance, like Mastodon does, could be really helpful for those tech. savvy enough to care (namely, I'm thinking, for telling whether your instance has gotten the latest updates yet or not); those who wouldn't be would probably not even notice, either way.

**Comment by trwnh** [comment]
Fixed in https://github.com/pixelfed/pixelfed/commit/6c03599d4473ab84f89f3a509cd9b32666cb0084
