### ISSUE TITLE
"Free software is important" is translated incorrectly in russian

### ISSUE THREAD

**Issue by vaartis** [pixelfed/project-website#61]
Currently it says that "Software that doesn't cost money is important", and not "free [as in freedom] software is important".I suggest changing "Бесплатный софт – это важно" to "Свободное ПО - это важно". That'd mean libre, rather than doesnt-cost-money.

**Comment by jalcine** [comment]
An important distinction. I think some have even leveraged the term "libre" in English spaces to highlight this as well.
