### ISSUE TITLE
No instructions for finding an instance

### ISSUE THREAD

**Issue by alanz** [pixelfed/project-website#72]
I recently saw on mastadon that pixelfed had been removed from the "best alternative to Instagram" list, because registrations are closed on `pixelfed.social`.

I decided to give pixelfed a try, but there is no indication anywhere on this web site that there are any other instances running, nor how to find one with open registrations.

**Comment by alanz** [comment]
Thinking about it, the trend seems to be to have `joinXXX.org` sites for fediverse services.
e.g. 
- https://joinmastodon.org
- https://joinpeertube.org

And I apologise for drive-by #somebody-should comments.

**Comment by mediaformat** [comment]
Same, I posted earlier that registrations were temporarily opened on pixelfed.social, had a few replies saying they missed the window. Pixelfed.org was the first place I thought to look. 

@alanz Switching social has a shortlist here: https://switching.social/ethical-alternatives-to-instagram/

**Comment by mediaformat** [comment]
I knew I'd seen somewhere listing the registration status of instances...
https://the-federation.info/pixelfed

**Comment by alanz** [comment]
I think the point is to make it really easy for someone who does not know about the fediverse to sign up, by finding an instance with open registration.

And in defense of pixelfed.social, when I looked again without a logged in account it *does* offer a link to a list of open instances, in tiny text at the bottom.
